ajout de contraintes
juliadebray/geeko-api pull request #10
Opened 2022-01-27 13:58 UTC by juliadebray

2022-01-27 14:50 UTC, TokaLazy requested changes

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/Customer.php
> +     *     max = 50,
Pourquoi limiter à 50 alors que la bdd peut aller jusqu'à 255 ?

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/Ingredient.php
> +     *     max = 50,
Pourquoi limiter à 50 alors que la bdd peut aller jusqu'à 255 ?

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/Ingredient.php
> +     *     max = 50,
Pourquoi limiter à 50 alors que la bdd peut aller jusqu'à 255 ?

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/IngredientType.php
>       */
Il manque le type.

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/IngredientType.php
>      #[Groups(['read:item', 'write:item'])]
Il manque le type.

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/Potion.php
>      #[Groups(['read:item', 'write:item', 'modify:item'])]
Il manque le type.

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/Potion.php
>       */
Il manque le type.

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/PotionType.php
> +     *     max = 50,
Pourquoi limiter à 50 alors que la bdd peut aller jusqu'à 255 ?

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/PotionType.php
> +     *     max = 50,
Pourquoi limiter à 50 alors que la bdd peut aller jusqu'à 255 ?

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/PotionType.php
> +     *     max = 250,
Pourquoi limiter à 250 alors que la bdd peut aller jusqu'à 255 ?

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/Tool.php
> +     *     max = 50,
Pourquoi limiter à 50 alors que la bdd peut aller jusqu'à 255 ?

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/Tool.php
> +     *     max = 50,
Pourquoi limiter à 50 alors que la bdd peut aller jusqu'à 255 ?

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/User.php
> +     *     max = 50,
Pourquoi limiter à 50 alors que la bdd peut aller jusqu'à 180 ?

2022-01-27 14:50 UTC, TokaLazy commented on src/Entity/User.php
>      #[Groups(['read:item', 'write:item'])]
Il manque le type.

2022-01-27 17:42 UTC, juliadebray commented on src/Entity/User.php
>      #[Groups(['read:item', 'write:item'])]
Le @Assert\Email vérifie si le type est bien string

2022-01-28 12:37 UTC, TokaLazy approved these changes

2022-01-28 12:38 UTC, merged